// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/jd-homepage/Calculator.tsx": () => import("../components/mockups/jd-homepage/Calculator.tsx"),
  "./components/mockups/jd-homepage/Dialogue.tsx": () => import("../components/mockups/jd-homepage/Dialogue.tsx"),
  "./components/mockups/jd-homepage/Evidence.tsx": () => import("../components/mockups/jd-homepage/Evidence.tsx")
};
