/**
 * Dev-logs ingest router
 *
 * Receives POSTs from Claude Code hook scripts running on developer machines.
 * Writes the entry into maintenance_logs so it counts toward
 * project_hosting_terms budgets exactly like a manually-entered log.
 *
 * Auth: x-jdcd-key header matched against env JDCD_DEV_LOG_KEY.
 * Mounted at /api/dev-logs.
 */

import { Router, type Request, type Response, type NextFunction } from "express";
import { z } from "zod";
import { storage } from "./storage";
import { db } from "./db";
import { projects, maintenanceLogs } from "@shared/schema";
import { and, eq, desc } from "drizzle-orm";

export const devLogsIngestRouter = Router();

function requireApiKey(req: Request, res: Response, next: NextFunction) {
  const provided = req.headers["x-jdcd-key"];
  const expected = process.env.JDCD_DEV_LOG_KEY;
  if (!expected) {
    return res.status(503).json({ error: "JDCD_DEV_LOG_KEY not configured on server" });
  }
  if (typeof provided !== "string" || provided !== expected) {
    return res.status(401).json({ error: "Invalid or missing x-jdcd-key" });
  }
  next();
}

const ingestSchema = z.object({
  projectId: z.number().int().positive(),
  logType: z.enum(["hosting", "development"]).optional(),
  sessionId: z.string().min(1),
  startedAt: z.string().datetime(),
  endedAt: z.string().datetime(),
  minutesSpent: z.number().int().min(0),
  // Auto-logs default to no billable cost; the field is optional and
  // defaults to 0. The hook records token API spend in the description
  // text instead — operational cost, not a charge to the project.
  estimatedCostCents: z.number().int().min(0).optional(),
  description: z.string().min(1),
  category: z.string().optional(),
});

devLogsIngestRouter.post("/ingest", requireApiKey, async (req, res, next) => {
  try {
    const parsed = ingestSchema.safeParse(req.body);
    if (!parsed.success) {
      return res.status(400).json({ error: "Invalid payload", details: parsed.error.flatten() });
    }
    const data = parsed.data;

    const [project] = await db
      .select({ id: projects.id, status: projects.status })
      .from(projects)
      .where(eq(projects.id, data.projectId));
    if (!project) {
      return res.status(404).json({ error: `Project ${data.projectId} not found` });
    }

    // If logType not specified, mirror the auto-conversion logic used elsewhere:
    // hosting-status projects → "hosting", everything else → "development".
    const logType =
      data.logType ?? (project.status === "hosting" ? "hosting" : "development");

    // log_date is a DATE (no time) — use the date the session ended, in UTC.
    const logDate = data.endedAt.slice(0, 10);

    const created = await storage.createMaintenanceLog({
      projectId: data.projectId,
      logDate,
      minutesSpent: data.minutesSpent,
      description: data.description,
      estimatedCostCents: data.estimatedCostCents ?? 0,
      category: data.category ?? "claude-code-session",
      logType,
      // No createdByUserId — this is a system entry from the hook.
      createdByUserId: null as any,
    });

    res.status(201).json({ id: created.id, logType, logDate });
  } catch (err) {
    next(err);
  }
});

// Lightweight health check the hook can probe to verify connectivity + auth.
devLogsIngestRouter.get("/ping", requireApiKey, (_req, res) => {
  res.json({ ok: true, ts: new Date().toISOString() });
});

// List Claude-Code auto-logged sessions across all projects.
// Used by the local regenerate-dev-logs.mjs migration script — lets it find
// stale broken-format descriptions without needing an admin browser session.
// Returns rows in createdAt-ASC order (oldest first) so the script can walk
// per-session slices in chronological order.
devLogsIngestRouter.get("/sessions", requireApiKey, async (_req, res, next) => {
  try {
    const rows = await db
      .select({
        id: maintenanceLogs.id,
        projectId: maintenanceLogs.projectId,
        logDate: maintenanceLogs.logDate,
        minutesSpent: maintenanceLogs.minutesSpent,
        description: maintenanceLogs.description,
        createdAt: maintenanceLogs.createdAt,
        logType: maintenanceLogs.logType,
      })
      .from(maintenanceLogs)
      .where(eq(maintenanceLogs.category, "claude-code-session"))
      .orderBy(maintenanceLogs.createdAt, maintenanceLogs.id);
    res.json({ count: rows.length, logs: rows });
  } catch (err) {
    next(err);
  }
});

// Update a Claude-Code auto-log's description (only). Used by the migration
// script to repair entries that were generated by the old fallback formatter.
// Scoped to category=claude-code-session so this can't be used to mutate
// human-entered logs.
const patchSchema = z.object({ description: z.string().min(1) });

devLogsIngestRouter.patch("/:id", requireApiKey, async (req, res, next) => {
  try {
    const id = parseInt(req.params.id, 10);
    if (!Number.isFinite(id) || id <= 0) {
      return res.status(400).json({ error: "invalid id" });
    }
    const parsed = patchSchema.safeParse(req.body);
    if (!parsed.success) {
      return res.status(400).json({ error: "Invalid payload", details: parsed.error.flatten() });
    }

    const [existing] = await db
      .select({ id: maintenanceLogs.id, category: maintenanceLogs.category })
      .from(maintenanceLogs)
      .where(eq(maintenanceLogs.id, id));
    if (!existing) {
      return res.status(404).json({ error: "log not found" });
    }
    if (existing.category !== "claude-code-session") {
      return res.status(403).json({ error: "this endpoint only updates claude-code-session logs" });
    }

    const [updated] = await db
      .update(maintenanceLogs)
      .set({ description: parsed.data.description })
      .where(and(eq(maintenanceLogs.id, id), eq(maintenanceLogs.category, "claude-code-session")))
      .returning({ id: maintenanceLogs.id });
    res.json({ id: updated.id });
  } catch (err) {
    next(err);
  }
});
